INSERT INTO "city" ("voivodeship", "name") VALUES (2,'Nowogrodziec');
INSERT INTO "city" ("voivodeship", "name") VALUES (2,'Pieszyce');
INSERT INTO "city" ("voivodeship", "name") VALUES (2,'Niemcza');
INSERT INTO "city" ("voivodeship", "name") VALUES (2,'Góra');
INSERT INTO "city" ("voivodeship", "name") VALUES (2,'Wąsosz');
INSERT INTO "city" ("voivodeship", "name") VALUES (2,'Bolków');
INSERT INTO "city" ("voivodeship", "name") VALUES (2,'Lubawka');
INSERT INTO "city" ("voivodeship", "name") VALUES (2,'Bystrzyca Kłodzka');
INSERT INTO "city" ("voivodeship", "name") VALUES (2,'Lądek-Zdrój');
INSERT INTO "city" ("voivodeship", "name") VALUES (2,'Międzylesie');
INSERT INTO "city" ("voivodeship", "name") VALUES (2,'Radków');
INSERT INTO "city" ("voivodeship", "name") VALUES (2,'Stronie Śląskie');
INSERT INTO "city" ("voivodeship", "name") VALUES (2,'Szczytna');
INSERT INTO "city" ("voivodeship", "name") VALUES (2,'Prochowice');
INSERT INTO "city" ("voivodeship", "name") VALUES (2,'Leśna');
INSERT INTO "city" ("voivodeship", "name") VALUES (2,'Olszyna');
INSERT INTO "city" ("voivodeship", "name") VALUES (2,'Ścinawa');
INSERT INTO "city" ("voivodeship", "name") VALUES (2,'Gryfów Śląski');
INSERT INTO "city" ("voivodeship", "name") VALUES (2,'Lubomierz');
INSERT INTO "city" ("voivodeship", "name") VALUES (2,'Lwówek Śląski');
INSERT INTO "city" ("voivodeship", "name") VALUES (2,'Mirsk');
INSERT INTO "city" ("voivodeship", "name") VALUES (2,'Wleń');
INSERT INTO "city" ("voivodeship", "name") VALUES (2,'Milicz');
INSERT INTO "city" ("voivodeship", "name") VALUES (2,'Bierutów');
INSERT INTO "city" ("voivodeship", "name") VALUES (2,'Międzybórz');
INSERT INTO "city" ("voivodeship", "name") VALUES (2,'Syców');
INSERT INTO "city" ("voivodeship", "name") VALUES (2,'Twardogóra');
INSERT INTO "city" ("voivodeship", "name") VALUES (2,'Jelcz-Laskowice');
INSERT INTO "city" ("voivodeship", "name") VALUES (2,'Chocianów');
INSERT INTO "city" ("voivodeship", "name") VALUES (2,'Polkowice');
INSERT INTO "city" ("voivodeship", "name") VALUES (2,'Przemków');
INSERT INTO "city" ("voivodeship", "name") VALUES (2,'Strzelin');
INSERT INTO "city" ("voivodeship", "name") VALUES (2,'Wiązów');
INSERT INTO "city" ("voivodeship", "name") VALUES (2,'Miękinia');
INSERT INTO "city" ("voivodeship", "name") VALUES (2,'Środa Śląska');
INSERT INTO "city" ("voivodeship", "name") VALUES (2,'Jaworzyna Śląska');
INSERT INTO "city" ("voivodeship", "name") VALUES (2,'Strzegom');
INSERT INTO "city" ("voivodeship", "name") VALUES (2,'Żarów');
INSERT INTO "city" ("voivodeship", "name") VALUES (2,'Oborniki Śląskie');
INSERT INTO "city" ("voivodeship", "name") VALUES (2,'Prusice');
INSERT INTO "city" ("voivodeship", "name") VALUES (2,'Trzebnica');
INSERT INTO "city" ("voivodeship", "name") VALUES (2,'Żmigród');
INSERT INTO "city" ("voivodeship", "name") VALUES (2,'Głuszyca');
INSERT INTO "city" ("voivodeship", "name") VALUES (2,'Mieroszów');
INSERT INTO "city" ("voivodeship", "name") VALUES (2,'Brzeg Dolny');
INSERT INTO "city" ("voivodeship", "name") VALUES (2,'Wołów');
INSERT INTO "city" ("voivodeship", "name") VALUES (2,'Kąty Wrocławskie');
INSERT INTO "city" ("voivodeship", "name") VALUES (2,'Sobótka');
INSERT INTO "city" ("voivodeship", "name") VALUES (2,'Siechnice');
INSERT INTO "city" ("voivodeship", "name") VALUES (2,'Bardo');
INSERT INTO "city" ("voivodeship", "name") VALUES (2,'Kamieniec Ząbkowicki');
INSERT INTO "city" ("voivodeship", "name") VALUES (2,'Ząbkowice Śląskie');
INSERT INTO "city" ("voivodeship", "name") VALUES (2,'Ziębice');
INSERT INTO "city" ("voivodeship", "name") VALUES (2,'Złoty Stok');
INSERT INTO "city" ("voivodeship", "name") VALUES (2,'Bogatynia');
INSERT INTO "city" ("voivodeship", "name") VALUES (2,'Pieńsk');
INSERT INTO "city" ("voivodeship", "name") VALUES (2,'Węgliniec');
INSERT INTO "city" ("voivodeship", "name") VALUES (2,'Świerzawa');
INSERT INTO "city" ("voivodeship", "name") VALUES (2,'Jelenia Góra');
INSERT INTO "city" ("voivodeship", "name") VALUES (2,'Legnica');
INSERT INTO "city" ("voivodeship", "name") VALUES (2,'Wrocław');
INSERT INTO "city" ("voivodeship", "name") VALUES (2,'Wałbrzych');
INSERT INTO "city" ("voivodeship", "name") VALUES (4,'Górzno');
INSERT INTO "city" ("voivodeship", "name") VALUES (4,'Jabłonowo Pomorskie');
INSERT INTO "city" ("voivodeship", "name") VALUES (4,'Koronowo');
INSERT INTO "city" ("voivodeship", "name") VALUES (4,'Solec Kujawski');
INSERT INTO "city" ("voivodeship", "name") VALUES (4,'Kowalewo Pomorskie');
INSERT INTO "city" ("voivodeship", "name") VALUES (4,'Łasin');
INSERT INTO "city" ("voivodeship", "name") VALUES (4,'Radzyń Chełmiński');
INSERT INTO "city" ("voivodeship", "name") VALUES (4,'Gniewkowo');
INSERT INTO "city" ("voivodeship", "name") VALUES (4,'Janikowo');
INSERT INTO "city" ("voivodeship", "name") VALUES (4,'Kruszwica');
INSERT INTO "city" ("voivodeship", "name") VALUES (4,'Pakość');
INSERT INTO "city" ("voivodeship", "name") VALUES (4,'Bobrowniki');
INSERT INTO "city" ("voivodeship", "name") VALUES (4,'Dobrzyń nad Wisłą');
INSERT INTO "city" ("voivodeship", "name") VALUES (4,'Kikół');
INSERT INTO "city" ("voivodeship", "name") VALUES (4,'Skępe');
INSERT INTO "city" ("voivodeship", "name") VALUES (4,'Mogilno');
INSERT INTO "city" ("voivodeship", "name") VALUES (4,'Strzelno');
INSERT INTO "city" ("voivodeship", "name") VALUES (4,'Kcynia');
INSERT INTO "city" ("voivodeship", "name") VALUES (4,'Mrocza');
INSERT INTO "city" ("voivodeship", "name") VALUES (4,'Nakło nad Notecią');
INSERT INTO "city" ("voivodeship", "name") VALUES (4,'Szubin');
INSERT INTO "city" ("voivodeship", "name") VALUES (4,'Piotrków Kujawski');
INSERT INTO "city" ("voivodeship", "name") VALUES (4,'Kamień Krajeński');
INSERT INTO "city" ("voivodeship", "name") VALUES (4,'Sępólno Krajeńskie');
INSERT INTO "city" ("voivodeship", "name") VALUES (4,'Więcbork');
INSERT INTO "city" ("voivodeship", "name") VALUES (4,'Nowe');
INSERT INTO "city" ("voivodeship", "name") VALUES (4,'Pruszcz');
INSERT INTO "city" ("voivodeship", "name") VALUES (4,'Świecie');
INSERT INTO "city" ("voivodeship", "name") VALUES (4,'Tuchola');
INSERT INTO "city" ("voivodeship", "name") VALUES (4,'Brześć Kujawski');
INSERT INTO "city" ("voivodeship", "name") VALUES (4,'Chodecz');
INSERT INTO "city" ("voivodeship", "name") VALUES (4,'Izbica Kujawska');
INSERT INTO "city" ("voivodeship", "name") VALUES (4,'Lubień Kujawski');
INSERT INTO "city" ("voivodeship", "name") VALUES (4,'Lubraniec');
INSERT INTO "city" ("voivodeship", "name") VALUES (4,'Barcin');
INSERT INTO "city" ("voivodeship", "name") VALUES (4,'Gąsawa');
INSERT INTO "city" ("voivodeship", "name") VALUES (4,'Janowiec Wielkopolski');
INSERT INTO "city" ("voivodeship", "name") VALUES (4,'Łabiszyn');
INSERT INTO "city" ("voivodeship", "name") VALUES (4,'Żnin');
INSERT INTO "city" ("voivodeship", "name") VALUES (4,'Bydgoszcz');
INSERT INTO "city" ("voivodeship", "name") VALUES (4,'Grudziądz');
INSERT INTO "city" ("voivodeship", "name") VALUES (4,'Toruń');
INSERT INTO "city" ("voivodeship", "name") VALUES (4,'Włocławek');
INSERT INTO "city" ("voivodeship", "name") VALUES (6,'Janów Podlaski');
INSERT INTO "city" ("voivodeship", "name") VALUES (6,'Piszczac');
INSERT INTO "city" ("voivodeship", "name") VALUES (6,'Frampol');
INSERT INTO "city" ("voivodeship", "name") VALUES (6,'Goraj');
INSERT INTO "city" ("voivodeship", "name") VALUES (6,'Józefów');
INSERT INTO "city" ("voivodeship", "name") VALUES (6,'Tarnogród');
INSERT INTO "city" ("voivodeship", "name") VALUES (6,'Turobin');
INSERT INTO "city" ("voivodeship", "name") VALUES (6,'Siedliszcze');
INSERT INTO "city" ("voivodeship", "name") VALUES (6,'Rejowiec');
INSERT INTO "city" ("voivodeship", "name") VALUES (6,'Janów Lubelski');
INSERT INTO "city" ("voivodeship", "name") VALUES (6,'Modliborzyce');
INSERT INTO "city" ("voivodeship", "name") VALUES (6,'Izbica');
INSERT INTO "city" ("voivodeship", "name") VALUES (6,'Annopol');
INSERT INTO "city" ("voivodeship", "name") VALUES (6,'Urzędów');
INSERT INTO "city" ("voivodeship", "name") VALUES (6,'Kamionka');
INSERT INTO "city" ("voivodeship", "name") VALUES (6,'Kock');
INSERT INTO "city" ("voivodeship", "name") VALUES (6,'Ostrów Lubelski');
INSERT INTO "city" ("voivodeship", "name") VALUES (6,'Bełżyce');
INSERT INTO "city" ("voivodeship", "name") VALUES (6,'Bychawa');
INSERT INTO "city" ("voivodeship", "name") VALUES (6,'Łęczna');
INSERT INTO "city" ("voivodeship", "name") VALUES (6,'Józefów nad Wisłą');
INSERT INTO "city" ("voivodeship", "name") VALUES (6,'Opole Lubelskie');
INSERT INTO "city" ("voivodeship", "name") VALUES (6,'Poniatowa');
INSERT INTO "city" ("voivodeship", "name") VALUES (6,'Parczew');
INSERT INTO "city" ("voivodeship", "name") VALUES (6,'Kazimierz Dolny');
INSERT INTO "city" ("voivodeship", "name") VALUES (6,'Końskowola');
INSERT INTO "city" ("voivodeship", "name") VALUES (6,'Kurów');
INSERT INTO "city" ("voivodeship", "name") VALUES (6,'Nałęczów');
INSERT INTO "city" ("voivodeship", "name") VALUES (6,'Wąwolnica');
INSERT INTO "city" ("voivodeship", "name") VALUES (6,'Czemierniki');
INSERT INTO "city" ("voivodeship", "name") VALUES (6,'Ryki');
INSERT INTO "city" ("voivodeship", "name") VALUES (6,'Piaski');
INSERT INTO "city" ("voivodeship", "name") VALUES (6,'Lubycza Królewska');
INSERT INTO "city" ("voivodeship", "name") VALUES (6,'Łaszczów');
INSERT INTO "city" ("voivodeship", "name") VALUES (6,'Tyszowce');
INSERT INTO "city" ("voivodeship", "name") VALUES (6,'Krasnobród');
INSERT INTO "city" ("voivodeship", "name") VALUES (6,'Szczebrzeszyn');
INSERT INTO "city" ("voivodeship", "name") VALUES (6,'Zwierzyniec');
INSERT INTO "city" ("voivodeship", "name") VALUES (6,'Biała Podlaska');
INSERT INTO "city" ("voivodeship", "name") VALUES (6,'Chełm');
INSERT INTO "city" ("voivodeship", "name") VALUES (6,'Lublin');
INSERT INTO "city" ("voivodeship", "name") VALUES (6,'Zamość');
INSERT INTO "city" ("voivodeship", "name") VALUES (8,'Witnica');
INSERT INTO "city" ("voivodeship", "name") VALUES (8,'Krosno Odrzańskie');
INSERT INTO "city" ("voivodeship", "name") VALUES (8,'Międzyrzecz');
INSERT INTO "city" ("voivodeship", "name") VALUES (8,'Skwierzyna');
INSERT INTO "city" ("voivodeship", "name") VALUES (8,'Trzciel');
INSERT INTO "city" ("voivodeship", "name") VALUES (8,'Bytom Odrzański');
INSERT INTO "city" ("voivodeship", "name") VALUES (8,'Kożuchów');
INSERT INTO "city" ("voivodeship", "name") VALUES (8,'Nowe Miasteczko');
INSERT INTO "city" ("voivodeship", "name") VALUES (8,'Otyń');
INSERT INTO "city" ("voivodeship", "name") VALUES (8,'Cybinka');
INSERT INTO "city" ("voivodeship", "name") VALUES (8,'Ośno Lubuskie');
INSERT INTO "city" ("voivodeship", "name") VALUES (8,'Rzepin');
INSERT INTO "city" ("voivodeship", "name") VALUES (8,'Słubice');
INSERT INTO "city" ("voivodeship", "name") VALUES (8,'Dobiegniew');
INSERT INTO "city" ("voivodeship", "name") VALUES (8,'Drezdenko');
INSERT INTO "city" ("voivodeship", "name") VALUES (8,'Strzelce Krajeńskie');
INSERT INTO "city" ("voivodeship", "name") VALUES (8,'Lubniewice');
INSERT INTO "city" ("voivodeship", "name") VALUES (8,'Sulęcin');
INSERT INTO "city" ("voivodeship", "name") VALUES (8,'Torzym');
INSERT INTO "city" ("voivodeship", "name") VALUES (8,'Świebodzin');
INSERT INTO "city" ("voivodeship", "name") VALUES (8,'Zbąszynek');
INSERT INTO "city" ("voivodeship", "name") VALUES (8,'Babimost');
INSERT INTO "city" ("voivodeship", "name") VALUES (8,'Czerwieńsk');
INSERT INTO "city" ("voivodeship", "name") VALUES (8,'Kargowa');
INSERT INTO "city" ("voivodeship", "name") VALUES (8,'Nowogród Bobrzański');
INSERT INTO "city" ("voivodeship", "name") VALUES (8,'Sulechów');
INSERT INTO "city" ("voivodeship", "name") VALUES (8,'Iłowa');
INSERT INTO "city" ("voivodeship", "name") VALUES (8,'Małomice');
INSERT INTO "city" ("voivodeship", "name") VALUES (8,'Szprotawa');
INSERT INTO "city" ("voivodeship", "name") VALUES (8,'Brody');
INSERT INTO "city" ("voivodeship", "name") VALUES (8,'Jasień');
INSERT INTO "city" ("voivodeship", "name") VALUES (8,'Lubsko');
INSERT INTO "city" ("voivodeship", "name") VALUES (8,'Sława');
INSERT INTO "city" ("voivodeship", "name") VALUES (8,'Szlichtyngowa');
INSERT INTO "city" ("voivodeship", "name") VALUES (8,'Wschowa');
INSERT INTO "city" ("voivodeship", "name") VALUES (8,'Gorzów Wielkopolski');
INSERT INTO "city" ("voivodeship", "name") VALUES (8,'Zielona Góra');
INSERT INTO "city" ("voivodeship", "name") VALUES (10,'Zelów');
INSERT INTO "city" ("voivodeship", "name") VALUES (10,'Dąbrowice');
INSERT INTO "city" ("voivodeship", "name") VALUES (10,'Krośniewice');
INSERT INTO "city" ("voivodeship", "name") VALUES (10,'Żychlin');
INSERT INTO "city" ("voivodeship", "name") VALUES (10,'Łask');
INSERT INTO "city" ("voivodeship", "name") VALUES (10,'Grabów');
INSERT INTO "city" ("voivodeship", "name") VALUES (10,'Piątek');
INSERT INTO "city" ("voivodeship", "name") VALUES (10,'Kiernozia');
INSERT INTO "city" ("voivodeship", "name") VALUES (10,'Koluszki');
INSERT INTO "city" ("voivodeship", "name") VALUES (10,'Rzgów');
INSERT INTO "city" ("voivodeship", "name") VALUES (10,'Tuszyn');
INSERT INTO "city" ("voivodeship", "name") VALUES (10,'Białaczów');
INSERT INTO "city" ("voivodeship", "name") VALUES (10,'Drzewica');
INSERT INTO "city" ("voivodeship", "name") VALUES (10,'Opoczno');
INSERT INTO "city" ("voivodeship", "name") VALUES (10,'Żarnów');
INSERT INTO "city" ("voivodeship", "name") VALUES (10,'Lutomiersk');
INSERT INTO "city" ("voivodeship", "name") VALUES (10,'Działoszyn');
INSERT INTO "city" ("voivodeship", "name") VALUES (10,'Pajęczno');
INSERT INTO "city" ("voivodeship", "name") VALUES (10,'Rozprza');
INSERT INTO "city" ("voivodeship", "name") VALUES (10,'Sulejów');
INSERT INTO "city" ("voivodeship", "name") VALUES (10,'Wolbórz');
INSERT INTO "city" ("voivodeship", "name") VALUES (10,'Poddębice');
INSERT INTO "city" ("voivodeship", "name") VALUES (10,'Uniejów');
INSERT INTO "city" ("voivodeship", "name") VALUES (10,'Kamieńsk');
INSERT INTO "city" ("voivodeship", "name") VALUES (10,'Przedbórz');
INSERT INTO "city" ("voivodeship", "name") VALUES (10,'Biała Rawska');
INSERT INTO "city" ("voivodeship", "name") VALUES (10,'Błaszki');
INSERT INTO "city" ("voivodeship", "name") VALUES (10,'Warta');
INSERT INTO "city" ("voivodeship", "name") VALUES (10,'Złoczew');
INSERT INTO "city" ("voivodeship", "name") VALUES (10,'Bolimów');
INSERT INTO "city" ("voivodeship", "name") VALUES (10,'Inowłódz');
INSERT INTO "city" ("voivodeship", "name") VALUES (10,'Ujazd');
INSERT INTO "city" ("voivodeship", "name") VALUES (10,'Osjaków');
INSERT INTO "city" ("voivodeship", "name") VALUES (10,'Wieluń');
INSERT INTO "city" ("voivodeship", "name") VALUES (10,'Bolesławiec');
INSERT INTO "city" ("voivodeship", "name") VALUES (10,'Lututów');
INSERT INTO "city" ("voivodeship", "name") VALUES (10,'Wieruszów');
INSERT INTO "city" ("voivodeship", "name") VALUES (10,'Szadek');
INSERT INTO "city" ("voivodeship", "name") VALUES (10,'Aleksandrów Łódzki');
INSERT INTO "city" ("voivodeship", "name") VALUES (10,'Parzęczew');
INSERT INTO "city" ("voivodeship", "name") VALUES (10,'Stryków');
INSERT INTO "city" ("voivodeship", "name") VALUES (10,'Jeżów');
INSERT INTO "city" ("voivodeship", "name") VALUES (10,'Łódź');
INSERT INTO "city" ("voivodeship", "name") VALUES (10,'Piotrków Trybunalski');
INSERT INTO "city" ("voivodeship", "name") VALUES (10,'Skierniewice');
INSERT INTO "city" ("voivodeship", "name") VALUES (12,'Nowy Wiśnicz');
INSERT INTO "city" ("voivodeship", "name") VALUES (12,'Brzesko');
INSERT INTO "city" ("voivodeship", "name") VALUES (12,'Czchów');
INSERT INTO "city" ("voivodeship", "name") VALUES (12,'Alwernia');
INSERT INTO "city" ("voivodeship", "name") VALUES (12,'Chrzanów');
INSERT INTO "city" ("voivodeship", "name") VALUES (12,'Libiąż');
INSERT INTO "city" ("voivodeship", "name") VALUES (12,'Trzebinia');
INSERT INTO "city" ("voivodeship", "name") VALUES (12,'Dąbrowa Tarnowska');
INSERT INTO "city" ("voivodeship", "name") VALUES (12,'Szczucin');
INSERT INTO "city" ("voivodeship", "name") VALUES (12,'Biecz');
INSERT INTO "city" ("voivodeship", "name") VALUES (12,'Bobowa');
INSERT INTO "city" ("voivodeship", "name") VALUES (12,'Krzeszowice');
INSERT INTO "city" ("voivodeship", "name") VALUES (12,'Skała');
INSERT INTO "city" ("voivodeship", "name") VALUES (12,'Skawina');
INSERT INTO "city" ("voivodeship", "name") VALUES (12,'Słomniki');
INSERT INTO "city" ("voivodeship", "name") VALUES (12,'Świątniki Górne');
INSERT INTO "city" ("voivodeship", "name") VALUES (12,'Książ Wielki');
INSERT INTO "city" ("voivodeship", "name") VALUES (12,'Miechów');
INSERT INTO "city" ("voivodeship", "name") VALUES (12,'Dobczyce');
INSERT INTO "city" ("voivodeship", "name") VALUES (12,'Myślenice');
INSERT INTO "city" ("voivodeship", "name") VALUES (12,'Sułkowice');
INSERT INTO "city" ("voivodeship", "name") VALUES (12,'Krynica-Zdrój');
INSERT INTO "city" ("voivodeship", "name") VALUES (12,'Muszyna');
INSERT INTO "city" ("voivodeship", "name") VALUES (12,'Piwniczna-Zdrój');
INSERT INTO "city" ("voivodeship", "name") VALUES (12,'Stary Sącz');
INSERT INTO "city" ("voivodeship", "name") VALUES (12,'Szczawnica');
INSERT INTO "city" ("voivodeship", "name") VALUES (12,'Czarny Dunajec');
INSERT INTO "city" ("voivodeship", "name") VALUES (12,'Rabka-Zdrój');
INSERT INTO "city" ("voivodeship", "name") VALUES (12,'Olkusz');
INSERT INTO "city" ("voivodeship", "name") VALUES (12,'Wolbrom');
INSERT INTO "city" ("voivodeship", "name") VALUES (12,'Brzeszcze');
INSERT INTO "city" ("voivodeship", "name") VALUES (12,'Chełmek');
INSERT INTO "city" ("voivodeship", "name") VALUES (12,'Kęty');
INSERT INTO "city" ("voivodeship", "name") VALUES (12,'Zator');
INSERT INTO "city" ("voivodeship", "name") VALUES (12,'Koszyce');
INSERT INTO "city" ("voivodeship", "name") VALUES (12,'Nowe Brzesko');
INSERT INTO "city" ("voivodeship", "name") VALUES (12,'Proszowice');
INSERT INTO "city" ("voivodeship", "name") VALUES (12,'Maków Podhalański');
INSERT INTO "city" ("voivodeship", "name") VALUES (12,'Ciężkowice');
INSERT INTO "city" ("voivodeship", "name") VALUES (12,'Radłów');
INSERT INTO "city" ("voivodeship", "name") VALUES (12,'Ryglice');
INSERT INTO "city" ("voivodeship", "name") VALUES (12,'Tuchów');
INSERT INTO "city" ("voivodeship", "name") VALUES (12,'Wojnicz');
INSERT INTO "city" ("voivodeship", "name") VALUES (12,'Zakliczyn');
INSERT INTO "city" ("voivodeship", "name") VALUES (12,'Żabno');
INSERT INTO "city" ("voivodeship", "name") VALUES (12,'Andrychów');
INSERT INTO "city" ("voivodeship", "name") VALUES (12,'Kalwaria Zebrzydowska');
INSERT INTO "city" ("voivodeship", "name") VALUES (12,'Wadowice');
INSERT INTO "city" ("voivodeship", "name") VALUES (12,'Niepołomice');
INSERT INTO "city" ("voivodeship", "name") VALUES (12,'Wieliczka');
INSERT INTO "city" ("voivodeship", "name") VALUES (12,'Kraków');
INSERT INTO "city" ("voivodeship", "name") VALUES (12,'Nowy Sącz');
INSERT INTO "city" ("voivodeship", "name") VALUES (12,'Tarnów');
INSERT INTO "city" ("voivodeship", "name") VALUES (14,'Białobrzegi');
INSERT INTO "city" ("voivodeship", "name") VALUES (14,'Wyśmierzyce');
INSERT INTO "city" ("voivodeship", "name") VALUES (14,'Glinojeck');
INSERT INTO "city" ("voivodeship", "name") VALUES (14,'Maciejowice');
INSERT INTO "city" ("voivodeship", "name") VALUES (14,'Pilawa');
INSERT INTO "city" ("voivodeship", "name") VALUES (14,'Żelechów');
INSERT INTO "city" ("voivodeship", "name") VALUES (14,'Sanniki');
INSERT INTO "city" ("voivodeship", "name") VALUES (14,'Grodzisk Mazowiecki');
INSERT INTO "city" ("voivodeship", "name") VALUES (14,'Grójec');
INSERT INTO "city" ("voivodeship", "name") VALUES (14,'Mogielnica');
INSERT INTO "city" ("voivodeship", "name") VALUES (14,'Nowe Miasto nad Pilicą');
INSERT INTO "city" ("voivodeship", "name") VALUES (14,'Warka');
INSERT INTO "city" ("voivodeship", "name") VALUES (14,'Głowaczów');
INSERT INTO "city" ("voivodeship", "name") VALUES (14,'Kozienice');
INSERT INTO "city" ("voivodeship", "name") VALUES (14,'Magnuszew');
INSERT INTO "city" ("voivodeship", "name") VALUES (14,'Serock');
INSERT INTO "city" ("voivodeship", "name") VALUES (14,'Ciepielów');
INSERT INTO "city" ("voivodeship", "name") VALUES (14,'Lipsko');
INSERT INTO "city" ("voivodeship", "name") VALUES (14,'Sienno');
INSERT INTO "city" ("voivodeship", "name") VALUES (14,'Solec nad Wisłą');
INSERT INTO "city" ("voivodeship", "name") VALUES (14,'Łosice');
INSERT INTO "city" ("voivodeship", "name") VALUES (14,'Różan');
INSERT INTO "city" ("voivodeship", "name") VALUES (14,'Cegłów');
INSERT INTO "city" ("voivodeship", "name") VALUES (14,'Dobre');
INSERT INTO "city" ("voivodeship", "name") VALUES (14,'Halinów');
INSERT INTO "city" ("voivodeship", "name") VALUES (14,'Kałuszyn');
INSERT INTO "city" ("voivodeship", "name") VALUES (14,'Latowicz');
INSERT INTO "city" ("voivodeship", "name") VALUES (14,'Mrozy');
INSERT INTO "city" ("voivodeship", "name") VALUES (14,'Siennica');
INSERT INTO "city" ("voivodeship", "name") VALUES (14,'Stanisławów');
INSERT INTO "city" ("voivodeship", "name") VALUES (14,'Nasielsk');
INSERT INTO "city" ("voivodeship", "name") VALUES (14,'Zakroczym');
INSERT INTO "city" ("voivodeship", "name") VALUES (14,'Myszyniec');
INSERT INTO "city" ("voivodeship", "name") VALUES (14,'Brok');
INSERT INTO "city" ("voivodeship", "name") VALUES (14,'Małkinia Górna');
INSERT INTO "city" ("voivodeship", "name") VALUES (14,'Karczew');
INSERT INTO "city" ("voivodeship", "name") VALUES (14,'Osieck');
INSERT INTO "city" ("voivodeship", "name") VALUES (14,'Góra Kalwaria');
INSERT INTO "city" ("voivodeship", "name") VALUES (14,'Konstancin-Jeziorna');
INSERT INTO "city" ("voivodeship", "name") VALUES (14,'Piaseczno');
INSERT INTO "city" ("voivodeship", "name") VALUES (14,'Tarczyn');
INSERT INTO "city" ("voivodeship", "name") VALUES (14,'Bodzanów');
INSERT INTO "city" ("voivodeship", "name") VALUES (14,'Drobin');
INSERT INTO "city" ("voivodeship", "name") VALUES (14,'Gąbin');
INSERT INTO "city" ("voivodeship", "name") VALUES (14,'Staroźreby');
INSERT INTO "city" ("voivodeship", "name") VALUES (14,'Wyszogród');
INSERT INTO "city" ("voivodeship", "name") VALUES (14,'Czerwińsk nad Wisłą');
INSERT INTO "city" ("voivodeship", "name") VALUES (14,'Nowe Miasto');
INSERT INTO "city" ("voivodeship", "name") VALUES (14,'Sochocin');
INSERT INTO "city" ("voivodeship", "name") VALUES (14,'Brwinów');
INSERT INTO "city" ("voivodeship", "name") VALUES (14,'Chorzele');
INSERT INTO "city" ("voivodeship", "name") VALUES (14,'Gielniów');
INSERT INTO "city" ("voivodeship", "name") VALUES (14,'Odrzywół');
INSERT INTO "city" ("voivodeship", "name") VALUES (14,'Przysucha');
INSERT INTO "city" ("voivodeship", "name") VALUES (14,'Pułtusk');
INSERT INTO "city" ("voivodeship", "name") VALUES (14,'Iłża');
INSERT INTO "city" ("voivodeship", "name") VALUES (14,'Jedlnia-Letnisko');
INSERT INTO "city" ("voivodeship", "name") VALUES (14,'Przytyk');
INSERT INTO "city" ("voivodeship", "name") VALUES (14,'Skaryszew');
INSERT INTO "city" ("voivodeship", "name") VALUES (14,'Mordy');
INSERT INTO "city" ("voivodeship", "name") VALUES (14,'Kosów Lacki');
INSERT INTO "city" ("voivodeship", "name") VALUES (14,'Jastrząb');
INSERT INTO "city" ("voivodeship", "name") VALUES (14,'Szydłowiec');
INSERT INTO "city" ("voivodeship", "name") VALUES (14,'Błonie');
INSERT INTO "city" ("voivodeship", "name") VALUES (14,'Łomianki');
INSERT INTO "city" ("voivodeship", "name") VALUES (14,'Ożarów Mazowiecki');
INSERT INTO "city" ("voivodeship", "name") VALUES (14,'Łochów');
INSERT INTO "city" ("voivodeship", "name") VALUES (14,'Jadów');
INSERT INTO "city" ("voivodeship", "name") VALUES (14,'Radzymin');
INSERT INTO "city" ("voivodeship", "name") VALUES (14,'Tłuszcz');
INSERT INTO "city" ("voivodeship", "name") VALUES (14,'Wołomin');
INSERT INTO "city" ("voivodeship", "name") VALUES (14,'Wyszków');
INSERT INTO "city" ("voivodeship", "name") VALUES (14,'Kazanów');
INSERT INTO "city" ("voivodeship", "name") VALUES (14,'Zwoleń');
INSERT INTO "city" ("voivodeship", "name") VALUES (14,'Bieżuń');
INSERT INTO "city" ("voivodeship", "name") VALUES (14,'Lubowidz');
INSERT INTO "city" ("voivodeship", "name") VALUES (14,'Żuromin');
INSERT INTO "city" ("voivodeship", "name") VALUES (14,'Mszczonów');
INSERT INTO "city" ("voivodeship", "name") VALUES (14,'Wiskitki');
INSERT INTO "city" ("voivodeship", "name") VALUES (14,'Ostrołęka');
INSERT INTO "city" ("voivodeship", "name") VALUES (14,'Płock');
INSERT INTO "city" ("voivodeship", "name") VALUES (14,'Radom');
INSERT INTO "city" ("voivodeship", "name") VALUES (14,'Siedlce');
INSERT INTO "city" ("voivodeship", "name") VALUES (14,'Warszawa');
INSERT INTO "city" ("voivodeship", "name") VALUES (16,'Grodków');
INSERT INTO "city" ("voivodeship", "name") VALUES (16,'Lewin Brzeski');
INSERT INTO "city" ("voivodeship", "name") VALUES (16,'Baborów');
INSERT INTO "city" ("voivodeship", "name") VALUES (16,'Branice');
INSERT INTO "city" ("voivodeship", "name") VALUES (16,'Głubczyce');
INSERT INTO "city" ("voivodeship", "name") VALUES (16,'Kietrz');
INSERT INTO "city" ("voivodeship", "name") VALUES (16,'Byczyna');
INSERT INTO "city" ("voivodeship", "name") VALUES (16,'Kluczbork');
INSERT INTO "city" ("voivodeship", "name") VALUES (16,'Wołczyn');
INSERT INTO "city" ("voivodeship", "name") VALUES (16,'Gogolin');
INSERT INTO "city" ("voivodeship", "name") VALUES (16,'Krapkowice');
INSERT INTO "city" ("voivodeship", "name") VALUES (16,'Strzeleczki');
INSERT INTO "city" ("voivodeship", "name") VALUES (16,'Zdzieszowice');
INSERT INTO "city" ("voivodeship", "name") VALUES (16,'Namysłów');
INSERT INTO "city" ("voivodeship", "name") VALUES (16,'Głuchołazy');
INSERT INTO "city" ("voivodeship", "name") VALUES (16,'Korfantów');
INSERT INTO "city" ("voivodeship", "name") VALUES (16,'Nysa');
INSERT INTO "city" ("voivodeship", "name") VALUES (16,'Otmuchów');
INSERT INTO "city" ("voivodeship", "name") VALUES (16,'Paczków');
INSERT INTO "city" ("voivodeship", "name") VALUES (16,'Dobrodzień');
INSERT INTO "city" ("voivodeship", "name") VALUES (16,'Gorzów Śląski');
INSERT INTO "city" ("voivodeship", "name") VALUES (16,'Olesno');
INSERT INTO "city" ("voivodeship", "name") VALUES (16,'Praszka');
INSERT INTO "city" ("voivodeship", "name") VALUES (16,'Niemodlin');
INSERT INTO "city" ("voivodeship", "name") VALUES (16,'Ozimek');
INSERT INTO "city" ("voivodeship", "name") VALUES (16,'Prószków');
INSERT INTO "city" ("voivodeship", "name") VALUES (16,'Tułowice');
INSERT INTO "city" ("voivodeship", "name") VALUES (16,'Biała');
INSERT INTO "city" ("voivodeship", "name") VALUES (16,'Głogówek');
INSERT INTO "city" ("voivodeship", "name") VALUES (16,'Prudnik');
INSERT INTO "city" ("voivodeship", "name") VALUES (16,'Kolonowskie');
INSERT INTO "city" ("voivodeship", "name") VALUES (16,'Leśnica');
INSERT INTO "city" ("voivodeship", "name") VALUES (16,'Strzelce Opolskie');
INSERT INTO "city" ("voivodeship", "name") VALUES (16,'Ujazd');
INSERT INTO "city" ("voivodeship", "name") VALUES (16,'Zawadzkie');
INSERT INTO "city" ("voivodeship", "name") VALUES (16,'Opole');
INSERT INTO "city" ("voivodeship", "name") VALUES (18,'Ustrzyki Dolne');
INSERT INTO "city" ("voivodeship", "name") VALUES (18,'Brzozów');
INSERT INTO "city" ("voivodeship", "name") VALUES (18,'Brzostek');
INSERT INTO "city" ("voivodeship", "name") VALUES (18,'Pilzno');
INSERT INTO "city" ("voivodeship", "name") VALUES (18,'Pruchnik');
INSERT INTO "city" ("voivodeship", "name") VALUES (18,'Kołaczyce');
INSERT INTO "city" ("voivodeship", "name") VALUES (18,'Kolbuszowa');
INSERT INTO "city" ("voivodeship", "name") VALUES (18,'Dukla');
INSERT INTO "city" ("voivodeship", "name") VALUES (18,'Iwonicz-Zdrój');
INSERT INTO "city" ("voivodeship", "name") VALUES (18,'Jedlicze');
INSERT INTO "city" ("voivodeship", "name") VALUES (18,'Rymanów');
INSERT INTO "city" ("voivodeship", "name") VALUES (18,'Nowa Sarzyna');
INSERT INTO "city" ("voivodeship", "name") VALUES (18,'Cieszanów');
INSERT INTO "city" ("voivodeship", "name") VALUES (18,'Narol');
INSERT INTO "city" ("voivodeship", "name") VALUES (18,'Oleszyce');
INSERT INTO "city" ("voivodeship", "name") VALUES (18,'Przecław');
INSERT INTO "city" ("voivodeship", "name") VALUES (18,'Radomyśl Wielki');
INSERT INTO "city" ("voivodeship", "name") VALUES (18,'Nisko');
INSERT INTO "city" ("voivodeship", "name") VALUES (18,'Rudnik nad Sanem');
INSERT INTO "city" ("voivodeship", "name") VALUES (18,'Ulanów');
INSERT INTO "city" ("voivodeship", "name") VALUES (18,'Bircza');
INSERT INTO "city" ("voivodeship", "name") VALUES (18,'Dubiecko');
INSERT INTO "city" ("voivodeship", "name") VALUES (18,'Jawornik Polski');
INSERT INTO "city" ("voivodeship", "name") VALUES (18,'Kańczuga');
INSERT INTO "city" ("voivodeship", "name") VALUES (18,'Sieniawa');
INSERT INTO "city" ("voivodeship", "name") VALUES (18,'Ropczyce');
INSERT INTO "city" ("voivodeship", "name") VALUES (18,'Sędziszów Małopolski');
INSERT INTO "city" ("voivodeship", "name") VALUES (18,'Błażowa');
INSERT INTO "city" ("voivodeship", "name") VALUES (18,'Boguchwała');
INSERT INTO "city" ("voivodeship", "name") VALUES (18,'Głogów Małopolski');
INSERT INTO "city" ("voivodeship", "name") VALUES (18,'Sokołów Małopolski');
INSERT INTO "city" ("voivodeship", "name") VALUES (18,'Tyczyn');
INSERT INTO "city" ("voivodeship", "name") VALUES (18,'Zagórz');
INSERT INTO "city" ("voivodeship", "name") VALUES (18,'Zaklików');
INSERT INTO "city" ("voivodeship", "name") VALUES (18,'Strzyżów');
INSERT INTO "city" ("voivodeship", "name") VALUES (18,'Baranów Sandomierski');
INSERT INTO "city" ("voivodeship", "name") VALUES (18,'Nowa Dęba');
INSERT INTO "city" ("voivodeship", "name") VALUES (18,'Lesko');
INSERT INTO "city" ("voivodeship", "name") VALUES (18,'Krosno');
INSERT INTO "city" ("voivodeship", "name") VALUES (18,'Przemyśl');
INSERT INTO "city" ("voivodeship", "name") VALUES (18,'Rzeszów');
INSERT INTO "city" ("voivodeship", "name") VALUES (18,'Tarnobrzeg');
INSERT INTO "city" ("voivodeship", "name") VALUES (20,'Lipsk');
INSERT INTO "city" ("voivodeship", "name") VALUES (20,'Choroszcz');
INSERT INTO "city" ("voivodeship", "name") VALUES (20,'Czarna Białostocka');
INSERT INTO "city" ("voivodeship", "name") VALUES (20,'Łapy');
INSERT INTO "city" ("voivodeship", "name") VALUES (20,'Michałowo');
INSERT INTO "city" ("voivodeship", "name") VALUES (20,'Supraśl');
INSERT INTO "city" ("voivodeship", "name") VALUES (20,'Suraż');
INSERT INTO "city" ("voivodeship", "name") VALUES (20,'Tykocin');
INSERT INTO "city" ("voivodeship", "name") VALUES (20,'Wasilków');
INSERT INTO "city" ("voivodeship", "name") VALUES (20,'Zabłudów');
INSERT INTO "city" ("voivodeship", "name") VALUES (20,'Rajgród');
INSERT INTO "city" ("voivodeship", "name") VALUES (20,'Szczuczyn');
INSERT INTO "city" ("voivodeship", "name") VALUES (20,'Kleszczele');
INSERT INTO "city" ("voivodeship", "name") VALUES (20,'Stawiski');
INSERT INTO "city" ("voivodeship", "name") VALUES (20,'Jedwabne');
INSERT INTO "city" ("voivodeship", "name") VALUES (20,'Nowogród');
INSERT INTO "city" ("voivodeship", "name") VALUES (20,'Goniądz');
INSERT INTO "city" ("voivodeship", "name") VALUES (20,'Knyszyn');
INSERT INTO "city" ("voivodeship", "name") VALUES (20,'Mońki');
INSERT INTO "city" ("voivodeship", "name") VALUES (20,'Drohiczyn');
INSERT INTO "city" ("voivodeship", "name") VALUES (20,'Dąbrowa Białostocka');
INSERT INTO "city" ("voivodeship", "name") VALUES (20,'Krynki');
INSERT INTO "city" ("voivodeship", "name") VALUES (20,'Sokółka');
INSERT INTO "city" ("voivodeship", "name") VALUES (20,'Suchowola');
INSERT INTO "city" ("voivodeship", "name") VALUES (20,'Ciechanowiec');
INSERT INTO "city" ("voivodeship", "name") VALUES (20,'Czyżew');
INSERT INTO "city" ("voivodeship", "name") VALUES (20,'Szepietowo');
INSERT INTO "city" ("voivodeship", "name") VALUES (20,'Białystok');
INSERT INTO "city" ("voivodeship", "name") VALUES (20,'Łomża');
INSERT INTO "city" ("voivodeship", "name") VALUES (20,'Suwałki');
INSERT INTO "city" ("voivodeship", "name") VALUES (22,'Bytów');
INSERT INTO "city" ("voivodeship", "name") VALUES (22,'Miastko');
INSERT INTO "city" ("voivodeship", "name") VALUES (22,'Brusy');
INSERT INTO "city" ("voivodeship", "name") VALUES (22,'Czersk');
INSERT INTO "city" ("voivodeship", "name") VALUES (22,'Czarne');
INSERT INTO "city" ("voivodeship", "name") VALUES (22,'Debrzno');
INSERT INTO "city" ("voivodeship", "name") VALUES (22,'Kartuzy');
INSERT INTO "city" ("voivodeship", "name") VALUES (22,'Żukowo');
INSERT INTO "city" ("voivodeship", "name") VALUES (22,'Prabuty');
INSERT INTO "city" ("voivodeship", "name") VALUES (22,'Nowy Staw');
INSERT INTO "city" ("voivodeship", "name") VALUES (22,'Nowy Dwór Gdański');
INSERT INTO "city" ("voivodeship", "name") VALUES (22,'Jastarnia');
INSERT INTO "city" ("voivodeship", "name") VALUES (22,'Władysławowo');
INSERT INTO "city" ("voivodeship", "name") VALUES (22,'Kępice');
INSERT INTO "city" ("voivodeship", "name") VALUES (22,'Kobylnica');
INSERT INTO "city" ("voivodeship", "name") VALUES (22,'Czarna Woda');
INSERT INTO "city" ("voivodeship", "name") VALUES (22,'Skarszewy');
INSERT INTO "city" ("voivodeship", "name") VALUES (22,'Gniew');
INSERT INTO "city" ("voivodeship", "name") VALUES (22,'Pelplin');
INSERT INTO "city" ("voivodeship", "name") VALUES (22,'Dzierzgoń');
INSERT INTO "city" ("voivodeship", "name") VALUES (22,'Sztum');
INSERT INTO "city" ("voivodeship", "name") VALUES (22,'Gdańsk');
INSERT INTO "city" ("voivodeship", "name") VALUES (22,'Gdynia');
INSERT INTO "city" ("voivodeship", "name") VALUES (22,'Słupsk');
INSERT INTO "city" ("voivodeship", "name") VALUES (22,'Sopot');
INSERT INTO "city" ("voivodeship", "name") VALUES (24,'Siewierz');
INSERT INTO "city" ("voivodeship", "name") VALUES (24,'Czechowice-Dziedzice');
INSERT INTO "city" ("voivodeship", "name") VALUES (24,'Wilamowice');
INSERT INTO "city" ("voivodeship", "name") VALUES (24,'Skoczów');
INSERT INTO "city" ("voivodeship", "name") VALUES (24,'Strumień');
INSERT INTO "city" ("voivodeship", "name") VALUES (24,'Blachownia');
INSERT INTO "city" ("voivodeship", "name") VALUES (24,'Janów');
INSERT INTO "city" ("voivodeship", "name") VALUES (24,'Koniecpol');
INSERT INTO "city" ("voivodeship", "name") VALUES (24,'Olsztyn');
INSERT INTO "city" ("voivodeship", "name") VALUES (24,'Przyrów');
INSERT INTO "city" ("voivodeship", "name") VALUES (24,'Sośnicowice');
INSERT INTO "city" ("voivodeship", "name") VALUES (24,'Toszek');
INSERT INTO "city" ("voivodeship", "name") VALUES (24,'Kłobuck');
INSERT INTO "city" ("voivodeship", "name") VALUES (24,'Krzepice');
INSERT INTO "city" ("voivodeship", "name") VALUES (24,'Woźniki');
INSERT INTO "city" ("voivodeship", "name") VALUES (24,'Koziegłowy');
INSERT INTO "city" ("voivodeship", "name") VALUES (24,'Żarki');
INSERT INTO "city" ("voivodeship", "name") VALUES (24,'Pszczyna');
INSERT INTO "city" ("voivodeship", "name") VALUES (24,'Krzanowice');
INSERT INTO "city" ("voivodeship", "name") VALUES (24,'Kuźnia Raciborska');
INSERT INTO "city" ("voivodeship", "name") VALUES (24,'Czerwionka-Leszczyny');
INSERT INTO "city" ("voivodeship", "name") VALUES (24,'Łazy');
INSERT INTO "city" ("voivodeship", "name") VALUES (24,'Ogrodzieniec');
INSERT INTO "city" ("voivodeship", "name") VALUES (24,'Pilica');
INSERT INTO "city" ("voivodeship", "name") VALUES (24,'Szczekociny');
INSERT INTO "city" ("voivodeship", "name") VALUES (24,'Włodowice');
INSERT INTO "city" ("voivodeship", "name") VALUES (24,'Bielsko-Biała');
INSERT INTO "city" ("voivodeship", "name") VALUES (24,'Bytom');
INSERT INTO "city" ("voivodeship", "name") VALUES (24,'Chorzów');
INSERT INTO "city" ("voivodeship", "name") VALUES (24,'Częstochowa');
INSERT INTO "city" ("voivodeship", "name") VALUES (24,'Dąbrowa Górnicza');
INSERT INTO "city" ("voivodeship", "name") VALUES (24,'Gliwice');
INSERT INTO "city" ("voivodeship", "name") VALUES (24,'Jastrzębie-Zdrój');
INSERT INTO "city" ("voivodeship", "name") VALUES (24,'Jaworzno');
INSERT INTO "city" ("voivodeship", "name") VALUES (24,'Katowice');
INSERT INTO "city" ("voivodeship", "name") VALUES (24,'Mysłowice');
INSERT INTO "city" ("voivodeship", "name") VALUES (24,'Piekary Śląskie');
INSERT INTO "city" ("voivodeship", "name") VALUES (24,'Ruda Śląska');
INSERT INTO "city" ("voivodeship", "name") VALUES (24,'Rybnik');
INSERT INTO "city" ("voivodeship", "name") VALUES (24,'Siemianowice Śląskie');
INSERT INTO "city" ("voivodeship", "name") VALUES (24,'Sosnowiec');
INSERT INTO "city" ("voivodeship", "name") VALUES (24,'Świętochłowice');
INSERT INTO "city" ("voivodeship", "name") VALUES (24,'Tychy');
INSERT INTO "city" ("voivodeship", "name") VALUES (24,'Zabrze');
INSERT INTO "city" ("voivodeship", "name") VALUES (24,'Żory');
INSERT INTO "city" ("voivodeship", "name") VALUES (26,'Busko-Zdrój');
INSERT INTO "city" ("voivodeship", "name") VALUES (26,'Nowy Korczyn');
INSERT INTO "city" ("voivodeship", "name") VALUES (26,'Pacanów');
INSERT INTO "city" ("voivodeship", "name") VALUES (26,'Stopnica');
INSERT INTO "city" ("voivodeship", "name") VALUES (26,'Wiślica');
INSERT INTO "city" ("voivodeship", "name") VALUES (26,'Jędrzejów');
INSERT INTO "city" ("voivodeship", "name") VALUES (26,'Małogoszcz');
INSERT INTO "city" ("voivodeship", "name") VALUES (26,'Sędziszów');
INSERT INTO "city" ("voivodeship", "name") VALUES (26,'Sobków');
INSERT INTO "city" ("voivodeship", "name") VALUES (26,'Wodzisław');
INSERT INTO "city" ("voivodeship", "name") VALUES (26,'Kazimierza Wielka');
INSERT INTO "city" ("voivodeship", "name") VALUES (26,'Opatowiec');
INSERT INTO "city" ("voivodeship", "name") VALUES (26,'Skalbmierz');
INSERT INTO "city" ("voivodeship", "name") VALUES (26,'Bodzentyn');
INSERT INTO "city" ("voivodeship", "name") VALUES (26,'Chęciny');
INSERT INTO "city" ("voivodeship", "name") VALUES (26,'Chmielnik');
INSERT INTO "city" ("voivodeship", "name") VALUES (26,'Daleszyce');
INSERT INTO "city" ("voivodeship", "name") VALUES (26,'Łagów');
INSERT INTO "city" ("voivodeship", "name") VALUES (26,'Łopuszno');
INSERT INTO "city" ("voivodeship", "name") VALUES (26,'Morawica');
INSERT INTO "city" ("voivodeship", "name") VALUES (26,'Nowa Słupia');
INSERT INTO "city" ("voivodeship", "name") VALUES (26,'Piekoszów');
INSERT INTO "city" ("voivodeship", "name") VALUES (26,'Pierzchnica');
INSERT INTO "city" ("voivodeship", "name") VALUES (26,'Gowarczów');
INSERT INTO "city" ("voivodeship", "name") VALUES (26,'Końskie');
INSERT INTO "city" ("voivodeship", "name") VALUES (26,'Radoszyce');
INSERT INTO "city" ("voivodeship", "name") VALUES (26,'Stąporków');
INSERT INTO "city" ("voivodeship", "name") VALUES (26,'Iwaniska');
INSERT INTO "city" ("voivodeship", "name") VALUES (26,'Opatów');
INSERT INTO "city" ("voivodeship", "name") VALUES (26,'Ożarów');
INSERT INTO "city" ("voivodeship", "name") VALUES (26,'Ćmielów');
INSERT INTO "city" ("voivodeship", "name") VALUES (26,'Kunów');
INSERT INTO "city" ("voivodeship", "name") VALUES (26,'Działoszyce');
INSERT INTO "city" ("voivodeship", "name") VALUES (26,'Pińczów');
INSERT INTO "city" ("voivodeship", "name") VALUES (26,'Klimontów');
INSERT INTO "city" ("voivodeship", "name") VALUES (26,'Koprzywnica');
INSERT INTO "city" ("voivodeship", "name") VALUES (26,'Zawichost');
INSERT INTO "city" ("voivodeship", "name") VALUES (26,'Suchedniów');
INSERT INTO "city" ("voivodeship", "name") VALUES (26,'Wąchock');
INSERT INTO "city" ("voivodeship", "name") VALUES (26,'Bogoria');
INSERT INTO "city" ("voivodeship", "name") VALUES (26,'Oleśnica');
INSERT INTO "city" ("voivodeship", "name") VALUES (26,'Osiek');
INSERT INTO "city" ("voivodeship", "name") VALUES (26,'Połaniec');
INSERT INTO "city" ("voivodeship", "name") VALUES (26,'Staszów');
INSERT INTO "city" ("voivodeship", "name") VALUES (26,'Szydłów');
INSERT INTO "city" ("voivodeship", "name") VALUES (26,'Włoszczowa');
INSERT INTO "city" ("voivodeship", "name") VALUES (26,'Kielce');
INSERT INTO "city" ("voivodeship", "name") VALUES (28,'Bisztynek');
INSERT INTO "city" ("voivodeship", "name") VALUES (28,'Sępopol');
INSERT INTO "city" ("voivodeship", "name") VALUES (28,'Frombork');
INSERT INTO "city" ("voivodeship", "name") VALUES (28,'Pieniężno');
INSERT INTO "city" ("voivodeship", "name") VALUES (28,'Lidzbark');
INSERT INTO "city" ("voivodeship", "name") VALUES (28,'Młynary');
INSERT INTO "city" ("voivodeship", "name") VALUES (28,'Pasłęk');
INSERT INTO "city" ("voivodeship", "name") VALUES (28,'Tolkmicko');
INSERT INTO "city" ("voivodeship", "name") VALUES (28,'Ryn');
INSERT INTO "city" ("voivodeship", "name") VALUES (28,'Kisielice');
INSERT INTO "city" ("voivodeship", "name") VALUES (28,'Susz');
INSERT INTO "city" ("voivodeship", "name") VALUES (28,'Zalewo');
INSERT INTO "city" ("voivodeship", "name") VALUES (28,'Korsze');
INSERT INTO "city" ("voivodeship", "name") VALUES (28,'Reszel');
INSERT INTO "city" ("voivodeship", "name") VALUES (28,'Orneta');
INSERT INTO "city" ("voivodeship", "name") VALUES (28,'Mikołajki');
INSERT INTO "city" ("voivodeship", "name") VALUES (28,'Nidzica');
INSERT INTO "city" ("voivodeship", "name") VALUES (28,'Olecko');
INSERT INTO "city" ("voivodeship", "name") VALUES (28,'Barczewo');
INSERT INTO "city" ("voivodeship", "name") VALUES (28,'Biskupiec');
INSERT INTO "city" ("voivodeship", "name") VALUES (28,'Dobre Miasto');
INSERT INTO "city" ("voivodeship", "name") VALUES (28,'Jeziorany');
INSERT INTO "city" ("voivodeship", "name") VALUES (28,'Olsztynek');
INSERT INTO "city" ("voivodeship", "name") VALUES (28,'Miłakowo');
INSERT INTO "city" ("voivodeship", "name") VALUES (28,'Miłomłyn');
INSERT INTO "city" ("voivodeship", "name") VALUES (28,'Morąg');
INSERT INTO "city" ("voivodeship", "name") VALUES (28,'Biała Piska');
INSERT INTO "city" ("voivodeship", "name") VALUES (28,'Orzysz');
INSERT INTO "city" ("voivodeship", "name") VALUES (28,'Pisz');
INSERT INTO "city" ("voivodeship", "name") VALUES (28,'Ruciane-Nida');
INSERT INTO "city" ("voivodeship", "name") VALUES (28,'Pasym');
INSERT INTO "city" ("voivodeship", "name") VALUES (28,'Wielbark');
INSERT INTO "city" ("voivodeship", "name") VALUES (28,'Gołdap');
INSERT INTO "city" ("voivodeship", "name") VALUES (28,'Węgorzewo');
INSERT INTO "city" ("voivodeship", "name") VALUES (28,'Elbląg');
INSERT INTO "city" ("voivodeship", "name") VALUES (28,'Olsztyn');
INSERT INTO "city" ("voivodeship", "name") VALUES (30,'Budzyń');
INSERT INTO "city" ("voivodeship", "name") VALUES (30,'Margonin');
INSERT INTO "city" ("voivodeship", "name") VALUES (30,'Szamocin');
INSERT INTO "city" ("voivodeship", "name") VALUES (30,'Krzyż Wielkopolski');
INSERT INTO "city" ("voivodeship", "name") VALUES (30,'Trzcianka');
INSERT INTO "city" ("voivodeship", "name") VALUES (30,'Wieleń');
INSERT INTO "city" ("voivodeship", "name") VALUES (30,'Czerniejewo');
INSERT INTO "city" ("voivodeship", "name") VALUES (30,'Kłecko');
INSERT INTO "city" ("voivodeship", "name") VALUES (30,'Trzemeszno');
INSERT INTO "city" ("voivodeship", "name") VALUES (30,'Witkowo');
INSERT INTO "city" ("voivodeship", "name") VALUES (30,'Borek Wielkopolski');
INSERT INTO "city" ("voivodeship", "name") VALUES (30,'Gostyń');
INSERT INTO "city" ("voivodeship", "name") VALUES (30,'Krobia');
INSERT INTO "city" ("voivodeship", "name") VALUES (30,'Pogorzela');
INSERT INTO "city" ("voivodeship", "name") VALUES (30,'Poniec');
INSERT INTO "city" ("voivodeship", "name") VALUES (30,'Grodzisk Wielkopolski');
INSERT INTO "city" ("voivodeship", "name") VALUES (30,'Rakoniewice');
INSERT INTO "city" ("voivodeship", "name") VALUES (30,'Wielichowo');
INSERT INTO "city" ("voivodeship", "name") VALUES (30,'Jaraczewo');
INSERT INTO "city" ("voivodeship", "name") VALUES (30,'Jarocin');
INSERT INTO "city" ("voivodeship", "name") VALUES (30,'Żerków');
INSERT INTO "city" ("voivodeship", "name") VALUES (30,'Koźminek');
INSERT INTO "city" ("voivodeship", "name") VALUES (30,'Opatówek');
INSERT INTO "city" ("voivodeship", "name") VALUES (30,'Stawiszyn');
INSERT INTO "city" ("voivodeship", "name") VALUES (30,'Kępno');
INSERT INTO "city" ("voivodeship", "name") VALUES (30,'Rychtal');
INSERT INTO "city" ("voivodeship", "name") VALUES (30,'Dąbie');
INSERT INTO "city" ("voivodeship", "name") VALUES (30,'Kłodawa');
INSERT INTO "city" ("voivodeship", "name") VALUES (30,'Przedecz');
INSERT INTO "city" ("voivodeship", "name") VALUES (30,'Golina');
INSERT INTO "city" ("voivodeship", "name") VALUES (30,'Kleczew');
INSERT INTO "city" ("voivodeship", "name") VALUES (30,'Rychwał');
INSERT INTO "city" ("voivodeship", "name") VALUES (30,'Sompolno');
INSERT INTO "city" ("voivodeship", "name") VALUES (30,'Ślesin');
INSERT INTO "city" ("voivodeship", "name") VALUES (30,'Czempiń');
INSERT INTO "city" ("voivodeship", "name") VALUES (30,'Krzywiń');
INSERT INTO "city" ("voivodeship", "name") VALUES (30,'Śmigiel');
INSERT INTO "city" ("voivodeship", "name") VALUES (30,'Kobylin');
INSERT INTO "city" ("voivodeship", "name") VALUES (30,'Koźmin Wielkopolski');
INSERT INTO "city" ("voivodeship", "name") VALUES (30,'Krotoszyn');
INSERT INTO "city" ("voivodeship", "name") VALUES (30,'Zduny');
INSERT INTO "city" ("voivodeship", "name") VALUES (30,'Osieczna');
INSERT INTO "city" ("voivodeship", "name") VALUES (30,'Rydzyna');
INSERT INTO "city" ("voivodeship", "name") VALUES (30,'Międzychód');
INSERT INTO "city" ("voivodeship", "name") VALUES (30,'Sieraków');
INSERT INTO "city" ("voivodeship", "name") VALUES (30,'Lwówek');
INSERT INTO "city" ("voivodeship", "name") VALUES (30,'Nowy Tomyśl');
INSERT INTO "city" ("voivodeship", "name") VALUES (30,'Opalenica');
INSERT INTO "city" ("voivodeship", "name") VALUES (30,'Zbąszyń');
INSERT INTO "city" ("voivodeship", "name") VALUES (30,'Oborniki');
INSERT INTO "city" ("voivodeship", "name") VALUES (30,'Rogoźno');
INSERT INTO "city" ("voivodeship", "name") VALUES (30,'Nowe Skalmierzyce');
INSERT INTO "city" ("voivodeship", "name") VALUES (30,'Odolanów');
INSERT INTO "city" ("voivodeship", "name") VALUES (30,'Raszków');
INSERT INTO "city" ("voivodeship", "name") VALUES (30,'Grabów nad Prosną');
INSERT INTO "city" ("voivodeship", "name") VALUES (30,'Mikstat');
INSERT INTO "city" ("voivodeship", "name") VALUES (30,'Ostrzeszów');
INSERT INTO "city" ("voivodeship", "name") VALUES (30,'Kaczory');
INSERT INTO "city" ("voivodeship", "name") VALUES (30,'Łobżenica');
INSERT INTO "city" ("voivodeship", "name") VALUES (30,'Miasteczko Krajeńskie');
INSERT INTO "city" ("voivodeship", "name") VALUES (30,'Ujście');
INSERT INTO "city" ("voivodeship", "name") VALUES (30,'Wyrzysk');
INSERT INTO "city" ("voivodeship", "name") VALUES (30,'Wysoka');
INSERT INTO "city" ("voivodeship", "name") VALUES (30,'Chocz');
INSERT INTO "city" ("voivodeship", "name") VALUES (30,'Dobrzyca');
INSERT INTO "city" ("voivodeship", "name") VALUES (30,'Pleszew');
INSERT INTO "city" ("voivodeship", "name") VALUES (30,'Buk');
INSERT INTO "city" ("voivodeship", "name") VALUES (30,'Kostrzyn');
INSERT INTO "city" ("voivodeship", "name") VALUES (30,'Kórnik');
INSERT INTO "city" ("voivodeship", "name") VALUES (30,'Mosina');
INSERT INTO "city" ("voivodeship", "name") VALUES (30,'Murowana Goślina');
INSERT INTO "city" ("voivodeship", "name") VALUES (30,'Pobiedziska');
INSERT INTO "city" ("voivodeship", "name") VALUES (30,'Stęszew');
INSERT INTO "city" ("voivodeship", "name") VALUES (30,'Swarzędz');
INSERT INTO "city" ("voivodeship", "name") VALUES (30,'Bojanowo');
INSERT INTO "city" ("voivodeship", "name") VALUES (30,'Jutrosin');
INSERT INTO "city" ("voivodeship", "name") VALUES (30,'Miejska Górka');
INSERT INTO "city" ("voivodeship", "name") VALUES (30,'Rawicz');
INSERT INTO "city" ("voivodeship", "name") VALUES (30,'Zagórów');
INSERT INTO "city" ("voivodeship", "name") VALUES (30,'Ostroróg');
INSERT INTO "city" ("voivodeship", "name") VALUES (30,'Pniewy');
INSERT INTO "city" ("voivodeship", "name") VALUES (30,'Szamotuły');
INSERT INTO "city" ("voivodeship", "name") VALUES (30,'Wronki');
INSERT INTO "city" ("voivodeship", "name") VALUES (30,'Środa Wielkopolska');
INSERT INTO "city" ("voivodeship", "name") VALUES (30,'Zaniemyśl');
INSERT INTO "city" ("voivodeship", "name") VALUES (30,'Dolsk');
INSERT INTO "city" ("voivodeship", "name") VALUES (30,'Książ Wielkopolski');
INSERT INTO "city" ("voivodeship", "name") VALUES (30,'Śrem');
INSERT INTO "city" ("voivodeship", "name") VALUES (30,'Dobra');
INSERT INTO "city" ("voivodeship", "name") VALUES (30,'Tuliszków');
INSERT INTO "city" ("voivodeship", "name") VALUES (30,'Gołańcz');
INSERT INTO "city" ("voivodeship", "name") VALUES (30,'Mieścisko');
INSERT INTO "city" ("voivodeship", "name") VALUES (30,'Skoki');
INSERT INTO "city" ("voivodeship", "name") VALUES (30,'Wolsztyn');
INSERT INTO "city" ("voivodeship", "name") VALUES (30,'Miłosław');
INSERT INTO "city" ("voivodeship", "name") VALUES (30,'Nekla');
INSERT INTO "city" ("voivodeship", "name") VALUES (30,'Pyzdry');
INSERT INTO "city" ("voivodeship", "name") VALUES (30,'Września');
INSERT INTO "city" ("voivodeship", "name") VALUES (30,'Jastrowie');
INSERT INTO "city" ("voivodeship", "name") VALUES (30,'Krajenka');
INSERT INTO "city" ("voivodeship", "name") VALUES (30,'Okonek');
INSERT INTO "city" ("voivodeship", "name") VALUES (30,'Kalisz');
INSERT INTO "city" ("voivodeship", "name") VALUES (30,'Konin');
INSERT INTO "city" ("voivodeship", "name") VALUES (30,'Leszno');
INSERT INTO "city" ("voivodeship", "name") VALUES (30,'Poznań');
INSERT INTO "city" ("voivodeship", "name") VALUES (32,'Karlino');
INSERT INTO "city" ("voivodeship", "name") VALUES (32,'Tychowo');
INSERT INTO "city" ("voivodeship", "name") VALUES (32,'Choszczno');
INSERT INTO "city" ("voivodeship", "name") VALUES (32,'Drawno');
INSERT INTO "city" ("voivodeship", "name") VALUES (32,'Pełczyce');
INSERT INTO "city" ("voivodeship", "name") VALUES (32,'Recz');
INSERT INTO "city" ("voivodeship", "name") VALUES (32,'Czaplinek');
INSERT INTO "city" ("voivodeship", "name") VALUES (32,'Drawsko Pomorskie');
INSERT INTO "city" ("voivodeship", "name") VALUES (32,'Kalisz Pomorski');
INSERT INTO "city" ("voivodeship", "name") VALUES (32,'Złocieniec');
INSERT INTO "city" ("voivodeship", "name") VALUES (32,'Goleniów');
INSERT INTO "city" ("voivodeship", "name") VALUES (32,'Maszewo');
INSERT INTO "city" ("voivodeship", "name") VALUES (32,'Nowogard');
INSERT INTO "city" ("voivodeship", "name") VALUES (32,'Stepnica');
INSERT INTO "city" ("voivodeship", "name") VALUES (32,'Gryfice');
INSERT INTO "city" ("voivodeship", "name") VALUES (32,'Płoty');
INSERT INTO "city" ("voivodeship", "name") VALUES (32,'Trzebiatów');
INSERT INTO "city" ("voivodeship", "name") VALUES (32,'Cedynia');
INSERT INTO "city" ("voivodeship", "name") VALUES (32,'Chojna');
INSERT INTO "city" ("voivodeship", "name") VALUES (32,'Gryfino');
INSERT INTO "city" ("voivodeship", "name") VALUES (32,'Mieszkowice');
INSERT INTO "city" ("voivodeship", "name") VALUES (32,'Moryń');
INSERT INTO "city" ("voivodeship", "name") VALUES (32,'Trzcińsko-Zdrój');
INSERT INTO "city" ("voivodeship", "name") VALUES (32,'Dziwnów');
INSERT INTO "city" ("voivodeship", "name") VALUES (32,'Golczewo');
INSERT INTO "city" ("voivodeship", "name") VALUES (32,'Kamień Pomorski');
INSERT INTO "city" ("voivodeship", "name") VALUES (32,'Międzyzdroje');
INSERT INTO "city" ("voivodeship", "name") VALUES (32,'Wolin');
INSERT INTO "city" ("voivodeship", "name") VALUES (32,'Gościno');
INSERT INTO "city" ("voivodeship", "name") VALUES (32,'Bobolice');
INSERT INTO "city" ("voivodeship", "name") VALUES (32,'Mielno');
INSERT INTO "city" ("voivodeship", "name") VALUES (32,'Polanów');
INSERT INTO "city" ("voivodeship", "name") VALUES (32,'Sianów');
INSERT INTO "city" ("voivodeship", "name") VALUES (32,'Barlinek');
INSERT INTO "city" ("voivodeship", "name") VALUES (32,'Dębno');
INSERT INTO "city" ("voivodeship", "name") VALUES (32,'Myślibórz');
INSERT INTO "city" ("voivodeship", "name") VALUES (32,'Nowe Warpno');
INSERT INTO "city" ("voivodeship", "name") VALUES (32,'Police');
INSERT INTO "city" ("voivodeship", "name") VALUES (32,'Lipiany');
INSERT INTO "city" ("voivodeship", "name") VALUES (32,'Pyrzyce');
INSERT INTO "city" ("voivodeship", "name") VALUES (32,'Chociwel');
INSERT INTO "city" ("voivodeship", "name") VALUES (32,'Dobrzany');
INSERT INTO "city" ("voivodeship", "name") VALUES (32,'Ińsko');
INSERT INTO "city" ("voivodeship", "name") VALUES (32,'Suchań');
INSERT INTO "city" ("voivodeship", "name") VALUES (32,'Barwice');
INSERT INTO "city" ("voivodeship", "name") VALUES (32,'Biały Bór');
INSERT INTO "city" ("voivodeship", "name") VALUES (32,'Borne Sulinowo');
INSERT INTO "city" ("voivodeship", "name") VALUES (32,'Połczyn-Zdrój');
INSERT INTO "city" ("voivodeship", "name") VALUES (32,'Człopa');
INSERT INTO "city" ("voivodeship", "name") VALUES (32,'Mirosławiec');
INSERT INTO "city" ("voivodeship", "name") VALUES (32,'Tuczno');
INSERT INTO "city" ("voivodeship", "name") VALUES (32,'Dobra');
INSERT INTO "city" ("voivodeship", "name") VALUES (32,'Łobez');
INSERT INTO "city" ("voivodeship", "name") VALUES (32,'Resko');
INSERT INTO "city" ("voivodeship", "name") VALUES (32,'Węgorzyno');
INSERT INTO "city" ("voivodeship", "name") VALUES (32,'Koszalin');
INSERT INTO "city" ("voivodeship", "name") VALUES (32,'Szczecin');
INSERT INTO "city" ("voivodeship", "name") VALUES (32,'Świnoujście');